### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by Alyn-zz** [graphql-community/ApolloAlamofire#1]
Hello,
I'm trying to integrate your lib to test apollo in background mode but it doesn't compile.

This line is in error (l.32) : 
`let body = ["query": type(of: operation).requestString, "variables": vars]`

I got an "Type 'Operation' has no member 'requestString'.
Can you tell me what I've missed ?

I'm on XCode 9.4, Swift 4.1.

Thx in advance,

EDIT: I manage to fix this issue (I think) by replacing `type(of: operation).requestString` with `operation.queryDocument`. Now, background websocket is not working but it's another issue :)

Aline

**Comment by MaxDesiatov** [comment]
Hi, thanks for the report and sorry for the delayed reply. What version of Apollo iOS library are you using?

**Comment by Alyn-zz** [comment]
Hello,

I'm using Apollo 0.9.0.
But I'm not using your lib anymore because we gave up using websocket in background :/

**Comment by MaxDesiatov** [comment]
I'm afraid background sessions won't be able to hold a persistent connection, so it makes sense to use WebSocket in foreground and plain `POST` endpoint in background. 

Could you please give more details on what problems specifically have you stumbled upon using WebSocket in background?

**Comment by Alyn-zz** [comment]
Well, callback method was not called and as Android team had also issues with websocket implementation, we decided to change to APNs before investigating any further.
Sorry i couldn't help you more... :/

thx anyway for your help !

**Comment by MaxDesiatov** [comment]
Fixed in version 0.3.0 of ApolloAlamofire.
