### ISSUE TITLE
Xcode 10.2 & Swift 5.0 compatibility

### ISSUE THREAD

**Issue by D-Link13** [graphql-community/ApolloAlamofire#2]
is it compatible for a new Xcode? Thanks!

**Comment by MaxDesiatov** [comment]
Hi @D-Link13, ApolloAlamofire itself doesn't have any code incompatible with Xcode 10.2/Swift 5.0, but unfortunately our main dependency has problems, see this issue for more details: apollographql/apollo-ios#485
