### ISSUE TITLE
Can I get http header response?

### ISSUE THREAD

**Issue by sarunw** [graphql-community/ApolloAlamofire#6]
Is there a way I can read http header of the response?

**Comment by MaxDesiatov** [comment]
Hi @sarunw, to my knowledge the GraphQL standard doesn't specify that GraphQL responses can pass any information in headers. If, for example, you need to read an authentication header from a REST endpoint, you can read that with plain Alamofire as usual and then use that to configure your `AlamofireTransport` instance. 

I probably could provide a better solution if I knew the context better. Would you be able to describe in more details what you're implementing?

**Comment by MaxDesiatov** [comment]
As this issue wasn't updated by the OP for a while, I assume it can be closed. Please feel free to reopen it with more details.
